### ISSUE TITLE
UB32 has faulty calculations

### ISSUE THREAD

**Issue by Butterhead98** [sh4rkman/SquadCalc#102]
UB32 has weird range calculations after 1500m exactly (range decreasing for a while on a flat plane) , maybe due to faulty values within the weapons.js UB32 range table?
Not a very technical guy, sorry, just here to bring it up

**Comment by sh4rkman** [comment]
Hey, thanks for reporting.
- is it on map mode, or classic mode or both?
- is it reproduced on every map ?

The UB32 calculations are the only one without a a real math formula, i just iterate the ingame table and approximate an elevation/velocity, it could definitly be wrong

**Comment by sh4rkman** [comment]
Corrected the faulty values : 
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/13038363-488c-42e2-b82e-73c6398feafe)

Will be deployed on squadcalc tonight/tomorrow

**Comment by sh4rkman** [comment]
Don't get me wrong, it's still very precise even considering the absurd spread of UB32 : The ingame table is very precise and i just approximate between table entries (aka if 900m is 10° and 1000m is 12°, 950m should be arround 11°).

Thats being said, i'm not calculating it because i'm bad at math, and the UB32 is the only weapon for witch the [projectile motion formula](https://en.wikipedia.org/wiki/Projectile_motion#Angle_%CE%B8_required_to_hit_coordinate_(x,_y)) (angle needed to hit a target with a given velocities) doesn't apply easily. I can't just slap the velocity found in the SDK (300m/s) on it and run the calc : it doesn't match the ingame table.

There is something else in the equation to introduce, most probably the rockets are slowly accelarating until reaching 300m/s, but my maths are not good enough to understand it. I'll give it a try again some day, but i gladely acept help to adapt this piece of code to work with UB32 : 

```
/**
 * Calculates the angle the mortar needs to be set in order
 * to hit the target at the desired distance and vertical delta.
 * @param {number} [dist] - distance between mortar and target from getDist()
 * @param {number} [vDelta] - vertical delta between mortar and target from getHeight()
 * @param {number} [vel] - initial mortar projectile velocity
 * @returns {number || NaN} radian angle if target in range, NaN otherwise
 */
function getElevation(dist = 0, vDelta = 0, vel = 0) {
    var gravity = globalData.gravity * globalData.activeWeapon.gravityScale;
    const P1 = Math.sqrt(vel ** 4 - gravity * (gravity * dist ** 2 + 2 * vDelta * vel ** 2));
    return Math.atan((vel ** 2 - (P1 * globalData.activeWeapon.getAngleType())) / (gravity * dist));
}
```
