### ISSUE TITLE
Standard mortar results are off (higher) by several milliradians

### ISSUE THREAD

**Issue by xuvvy** [sh4rkman/SquadCalc#107]
Comparing the SquadCalc mortar calculator to another mortar calculator shows that there is a discrepancy in calculation, possibly due to rounding errors, misinterpretation of the Squad height map or miscalculation, which can lead to several milliradians worth of error. The same exact point on any map has a consistently different milliradians result, meanwhile the stated angle is the same.

I have tested this on a live Squad server and across several maps and it seems like SquadCalc is always showing the standard mortar target angle to be several milliradians higher than actual, which results in mortar shots potentially falling marginally short. This result is consistent across servers and across maps.

Below are the images of the calculation from sqmortar.farssi.net (previously known as squadmortar.xyz) and SquadCalc for reference.

![image](https://github.com/sh4rkman/SquadCalc/assets/21984783/bba09f72-3fa9-415d-b629-895a748dfd23)
![image](https://github.com/sh4rkman/SquadCalc/assets/21984783/eff42216-ab61-407e-8cd4-95c6437d255f)

Depending on where the issue lies in the code, it is possible that this issue is also the case for other projectiles, but I have only tested this in-game for the Standard Mortar emplacement.

**Comment by sh4rkman** [comment]
There is a lot a parameters used by calculators that could explain a difference between their calculations and ingame results but here are the main one that could explain a difference :
- **map size**: used to calculate the raw distance in meter between two points on the map
- **weapon velocity** : used to calculate angle needed to hit a target at previously caculated distance
- **heightmap z-scaling** : used to calculate height difference in meters between two points on the map, impacting previously calculated angle

Since squadcalc and squadxyz both display the same distance in meter in everymap i have tried, and we both place the grid in the same exact way, i'm excluding the map size from the faulty parameters.

Now if i compare the same mortar/target calc in a situation where there is no heights difference between them, we found the same calculations. For this example the simplest test is to place both target and mortar on Kokan fields because it's pretty much the same height everywhere on the map

![20231210_11h21m_iB5JYoV5gn2](https://github.com/sh4rkman/SquadCalc/assets/9033912/6b6a1ff6-af5d-4866-b7db-8878246947bd)
_(left: xyz / right: squadcalc, i'm rounding number but this is irrelevant)_

That means that any differences between my calcs and xyz one's should be caused by the way we deduce from heightmaps the vertical difference in meter between weapon and target. 

--

So who is closer to ingame reality ? Well, first a really important point : at long range, you'll need a lot of milliradians to cover an extra 10m, what i mean is that the closer we get to max range (45° - 820milrad),  the difference between squadcalc and xyz will appear bigger, even if in reality that means 1m diff ingame. What i mean is that, and you'll see in the next screenshots, the difference between shooting @ 987.8 versus 995 is less than 2 meters ingame. 

That being said, to check who is more accurate in reality i set up a similar situation to your screenshot in the two calculators and ingame :  https://imgur.com/a/V34t8pW 

For the same weapon/target squadcalc says 995 and xyz 987, i ran 6 test shots for each : 
- SquadXYZ: https://imgur.com/a/kx6mgJ6
- SquadCalc : https://imgur.com/a/FdT6OSu

See, the difference looks like less than a meter. Compiling all the shots in one image : 

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/f2d3d18e-e00e-4f19-a450-1995b1ece8c2)


I'd say squadcalc is more precise after this test, mostly because it has 5 shots in a 2meter radius from target, when squad xyz has 4, but there is too much randomness due to spread that its difficult to say. If you find a calculation that is actually really wrong i'll investigate more, but as it is now i'd considere Gorodok very precise, and maybe more that xyz

**Comment by sh4rkman** [comment]
alright i've extracted the Gorodok heightmap again from the SDK and this time scrupulously adjusted the vertical ratio : now squadcalc display 991 for this example, witch is right inbetween actual squadcalc (995 and xyz (987). Mortars should be pixel perfect now on Gorodok.

If you have another example of map where shots are off i'd be happy to correct it.
I have already spotted inconsistency/light heightmap deviations on : 
- Goose bay
- Al Basrah
- Fallujah
