### ISSUE TITLE
Map Skorpo has been updated.

### ISSUE THREAD

**Issue by peter5he1by** [sh4rkman/SquadCalc#130]
I think Skorpo has been updated since Squad 7.2. But Idk how to extract the map and update this tool.

So plz could the author help us?

:)

**Comment by sh4rkman** [comment]
Are you sure the minimap image moved or is it just the grid alignment ? (Skorpo is a bit special and has several grid setup: same minimap image but cropped differently with new grid alignment)

I'm not home and cannot check the game/SDK right now, but if you can provide a screenshot already it will help me understand

**Comment by sh4rkman** [comment]
Okay, i have already seen this in the past it's not new to 7.2. if i remember correctly they introduced this setup with reworked top islands and restricted it to 1 invasion layer for testing purpose. 

Did they extended this version to all classic aas/raas ? I'll check when ill be back home this weekend.

If they have a few layers in one setup and the others in another i'll have to choose because i dont wanna propose several minimap/layer for each map atm

**Comment by sh4rkman** [comment]
Alright so they indeed grouped every pre-7.2 RAAS/AAS layers under one single layer that can be customised with factions, witch means no more "skorpo town" layer with different grid. And they indeed choose the "new" skorpo map with reworked islands and a _greener_ look. 

I updated map & heightmap, they should be accurate to ingame reality but let me know if i need to adjust precision. 

That being said, OWI fucked up again and they will need to fix skorpo : map image is a scare stretched on a ingame rectangle, resulting on the map being misaligned with the terrain. You can observe this by placing a marker ingame : it pops a few metters away to the east of where you intented to place it. I'll adapt squadcalc when (if?) they patch it.

Thanks a lot for reporting the issue !
