### ISSUE TITLE
I think heightmap is better than use json

### ISSUE THREAD

**Issue by zoslcne** [sh4rkman/SquadCalc#240]
Is there any way to fix the heightmap? putImageData?

![2024-12-07 135555](https://github.com/user-attachments/assets/dd570595-c500-4413-ab66-63d3a132ca2d)

**Comment by sh4rkman** [comment]
That's a old version of the heightmap that have been fixed since then, just get the current skorpo/heightmap.webp version from here, or [extract it on your own ](https://github.com/sh4rkman/SquadCalc/wiki/Adding-new-map) from the SDK if you want to fix your fork

Some heightmaps seems to have suffer from me manipulating/resizing/encoding them in .webp and faulty pixels can happen.
I manually correct them when i get report.

---

json is just a .webp format in a big array : if there is a problem with json, there is also one with the .webp. There should be no difference whatsoever, it should even be faster since json are loaded in memory and heights precalculated.

The problem with drawing heightmaps in a canvas and reading value with getImageData() is that it's getting more and more blocked by browsers in their attempt to [block fingerprinting](https://browserleaks.com/canvas).

**Comment by zoslcne** [comment]
Tallil
    map dimensions: [4680,4680], scale: [1,1,1.25]
    orig heightmap: 4573x4573
       final scale: 0.052750000000000005
scale heightmap to: 4573x4573
set canvas size to: 4680x4680
       with offset: 308x308
scaled heightmap still too small!
     set levels to: 3689 <-> 4111
     
     I don't know how to use Gimp. How do I set this with offset: 308x308?

**Comment by zoslcne** [comment]
Tallil
    map dimensions: [4680,4680], scale: [1,1,1.25]
    orig heightmap: 4573x4573
       final scale: 0.052750000000000005
scale heightmap to: 4573x4573
set canvas size to: 4680x4680
       with offset: 308x308
scaled heightmap still too small!
     set levels to: 3689 <-> 4111
I don't know how to use Gimp. How do I set this with offset: 308x308?
![175529](https://github.com/user-attachments/assets/0d4a7426-f690-4125-8293-857b7d0504b6)

**Comment by zoslcne** [comment]
The json is too large. I'd better replace the wrong coordinate data with other nearby coordinate data.

**Comment by zoslcne** [comment]
I have solved it by code

**Comment by sh4rkman** [comment]
Great ! Yeah the json isn't mean to be manually edited, the idea is to extract/work the image and run a script to manually convert it to pre-calculated json for production, avoiding canvas blocking browsers/extensions.
