### ISSUE TITLE
Addition of map interface

### ISSUE THREAD

**Issue by TheGrimReaper13** [sh4rkman/SquadCalc#68]
Considering squadmortar.xyz and squad-calc.com are not being kept up to date it would be great to add an option to use a map interface to place the weapon and targets.

**Comment by sh4rkman** [comment]
The whole philosophy of the project, _besides me kinda learning how to code_, was to offer an alternative to map-based calculators which could be clunky and annoying at times when it came to finding th right square in the middle of a desert area. I wanted a simple, minimalist calculator with no funky icons and map.

Even if squadmc/xyz aren't updated, the later one is still a solid alternative for most of the usecases (just don't use the techie/hellmortar it got the calcs wrong) : i won't bother recreate xyz, specially because i'm already working on another squad-map-based project , and don't have enough time for that.

If the author of xyz officially stated that he won't update his calculator and won't accept pull requests, well it's time to find someone ready to fork the project
